### ISSUE TITLE
swig dependency

### ISSUE THREAD

**Issue by SteveDiamond** [jacklzhu/CVXcanon#1]
Before this makes it into the cvxpy on pip, I'd like to simplify the swig dependency. The easiest approach is to compile CVXstoch for different platforms and put the distributions on pypi. That way people will only need swig if they're installing on non-standard platforms.

**Comment by millerjohnp** [comment]
There is a now a CVXcanon wheel on pypi for MacOSx. However, I wasn't able to create a wheel for linux since linux wheels are not currently supported on pypi. Do you have any idea how to work around this?

**Comment by SteveDiamond** [comment]
I'm not sure how to get around the Linux wheel issue. Not having a Linux
wheel is ok, since you can expect a bit more from Linux users.
