### ISSUE TITLE
version 0.0.22 is missing from github

### ISSUE THREAD

**Issue by mindw** [jacklzhu/CVXcanon#11]
Please tag and push the versions to allow notifications/tracking.

**Comment by mcg1969** [comment]
Yes, please do

**Comment by millerjohnp** [comment]
I just tagged and released version 0.0.22. 

I'm still getting up to speed with versioning and want to make the package as easy to distribute as possible. Please let me know if the tags/versioning is suboptimal or could be improved in any way!
