### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by mcg1969** [jacklzhu/CVXcanon#13]
From `__init__.py`:

> `from cvxpy.lin_ops.lin_op import *`

If the intention of this library is to offer "cvx-independent" capability, then it needs to be possible to build and test it without cvxpy. If the module depends critically on cvxpy functionality, then that functionality either needs to be moved to CVXcanon, or this module should just be included within cvxpy itself until such time as the separation makes more sense.

**Comment by SteveDiamond** [comment]
This is fixed now.
