### ISSUE TITLE
cvxpy memory usage

### ISSUE THREAD

**Issue by irenatfh** [jacklzhu/CVXcanon#23]
I'm using cvxpy version 0.4.0 on python 3.4.3 and have been seeing excessive memory usage when calling a function that solves a matrix optimization problem using cvxpy in a for loop. It sounded similar to [this](https://github.com/cvxgrp/cvxpy/issues/166) issue which was apparently resolved, but when I ran the same code snippet from the resolved issue on my computer I noticed that memory usage (monitored through >> top) still seems to be increasing with the loop. For prob.solve() with arguments CVXOPT, ECOS, SCS, or no argument, memory usage increased from about 40 kB at the start to about 300 kB after the last loop. While 300 kB isn't a huge deal for this test case of 10000 loops, it turns into tens of GB after billions of loops.

I posted this issue to the cvxpy Google Groups and was told that it might be an issue with CVXcanon, so I'm reposting the question here.

**Comment by mwytock** [comment]
Can you share a simple script that exhibits the behavior.

**Comment by irenatfh** [comment]
Sure, this is ripped almost directly from the [issue](https://github.com/cvxgrp/cvxpy/issues/166) I referenced in my first post:

```
import numpy as np
from cvxpy import *

def cvx_solve():
    m = 128
    n = 10
    np.random.seed(1)
    A = np.random.randn(m, n)
    b = np.random.randn(m)

    # Construct the problem.
    x = Variable(n)
    objective = Minimize(norm(A*x - b))
    constraints = [0 <= x, x <= 1]
    prob = Problem(objective, constraints)
    # prob.solve()
    # prob.solve('SCS')
    # prob.solve('ECOS')
    prob.solve('CVXOPT')

if __name__=='__main__':
    iterations = 10000
    for _ in range(iterations):
        cvx_solve()
```

If iterations is small, say, on the order of 10000, then cvxpy eats up about 300 kB by the time it completes all 10000 loops. However, when iterations is very large, say, 1000000000, then cvxpy eats up tens of GB, which is not sustainable.

**Comment by irenatfh** [comment]
I should add that I'm running Scipy 0.17.0 and Numpy 1.11.0. Are there any other packages I should update for cvxpy to run and do memory cleanup properly?

**Comment by mwytock** [comment]
If i use the code you provided verbatim with `range()` and change 10000 to 1000000000 then I definitely see the Python process consuming a bunch of memory, but if I simply change `range()` to `xrange()` then this issue goes away. Is this the problem you are seeing?

Besides this issue, everything seems fine with all 3 solvers, i.e. the memory usage remains bounded at a low level. I added a print in the loop

```
        if i % 100 == 0:
            print i
```

and when I run with a profile-enabled malloc (see http://goog-perftools.sourceforge.net/doc/heap_profiler.html)

I get something like  this output:

```
...
12000
12100
Dumping heap profile to /tmp/prof_46783.0017.heap (17408 MB allocated cumulatively, 9 MB currently in use)
12200
12300
12400
12500
12600
12700
12800
12900
Dumping heap profile to /tmp/prof_46783.0018.heap (18432 MB allocated cumulatively, 8 MB currently in use)
13000
13100
13200
13300
...
```

If you are still seeing memory problems, can you try using this profiler and post your results?

**Comment by irenatfh** [comment]
Thanks for your response! I don't think that the result you described is the problem I'm seeing since I'm running the test script using Python3, and range should be equivalent to Python2's xrange.

I'm happy to use a profiler and post my results, but very basic question: how exactly do I run the test Python script with the suggested profile-enabled malloc? I tried entering something like $ LD_PRELOAD=/usr/lib/libtcmalloc.so HEAPPROFILE=path_to_put_file $python3 path_to_test.py in a bash shell, but am told "Permission denied." Is there software I need to download in order to use this profiler, or does it come standard on most linux machines? Thanks in advance.

**Comment by mwytock** [comment]
that is true re: `xrange()` - what python version are you using? what linux version?

libtcmalloc.so is part of the perftools package from Google which is available via most package systems (e.g. apt-get, brew, etc.)

**Comment by irenatfh** [comment]
I'm using Python 3.4.3, Ubuntu 14.04.2 LTS.

sudo apt-get install libtcmalloc-minimal4 worked! However, I'm still having issues preloading it.

**Comment by mwytock** [comment]
RE: tcmalloc the perftools documentation should be able to help.

Using any method, if you could provide us with some data along the lines of  

num iterations, memory used
...
num iterations, memory used

that would be very helpful in debugging

**Comment by irenatfh** [comment]
Ok! Here's the heap profile for the first few thousands of iterations:

> Dumping heap profile to /tmp/.0001.heap (1024 MB allocated cumulatively, 23 MB currently in use)
> 1000
> 1100
> 1200
> 1300
> 1400
> 1500
> 1600
> 1700
> 1800
> 1900
> Dumping heap profile to /tmp/.0002.heap (2048 MB allocated cumulatively, 38 MB currently in use)
> 2000
> 2100
> 2200
> 2300
> 2400
> 2500
> 2600
> 2700
> 2800
> 2900
> Dumping heap profile to /tmp/.0003.heap (3072 MB allocated cumulatively, 54 MB currently in use)
> 3000
> 3100
> 3200
> 3300
> 3400
> 3500
> 3600
> 3700
> 3800
> 3900
> Dumping heap profile to /tmp/.0004.heap (4096 MB allocated cumulatively, 70 MB currently in use)
> 4000
> 4100
> 4200
> 4300
> 4400
> 4500
> 4600
> 4700
> 4800
> 4900
> Dumping heap profile to /tmp/.0005.heap (5120 MB allocated cumulatively, 85 MB currently in use)
> 5000
> 5100
> 5200
> 5300
> 5400
> 5500
> 5600
> 5700
> 5800
> 5900
> Dumping heap profile to /tmp/.0006.heap (6144 MB allocated cumulatively, 102 MB currently in use)

Tens of thousands of iterations later:

> Dumping heap profile to /tmp/.0077.heap (78848 MB allocated cumulatively, 1210 MB currently in use)
> 77500
> 77600
> 77700
> 77800
> 77900
> 78000
> 78100
> 78200
> 78300
> 78400
> Dumping heap profile to /tmp/.0078.heap (79872 MB allocated cumulatively, 1225 MB currently in use)
> 78500
> 78600
> 78700
> 78800
> 78900
> 79000
> 79100
> 79200
> 79300
> 79400
> Dumping heap profile to /tmp/.0079.heap (80896 MB allocated cumulatively, 1241 MB currently in use)
> 79500
> 79600
> 79700
> 79800
> 79900
> 80000
> 80100
> 80200
> 80300
> 80400
> Dumping heap profile to /tmp/.0080.heap (81920 MB allocated cumulatively, 1256 MB currently in use)

As far as I can tell, memory usage is monotonically increasing. Also, this is for the ECOS solver.

**Comment by mwytock** [comment]
Definitely looks like a memory leak which is different from what I saw when running your script. I will try to recreate the issue with your environment. 

One more thing, can you include the output of

```
pip list | grep 'cvxpy\|CVXcanon\|scs\|ecos\|cvxopt'
```

**Comment by irenatfh** [comment]
(Using pip3 because I installed cvxpy for Python3)

Oddly, `pip3 list | grep 'cvxpy|CVXcanon|scs|ecos|cvxopt'` outputs nothing, but here are the results for each of the arguments individually:
cvxpy (0.4.0)
CVXcanon (0.0.23.4)
scs (1.2.6)
ecos (2.0.4)
cvxopt (1.1.8)

**Comment by mwytock** [comment]
I was able to recreate your problem and it indeed seems to be specific to python3.

After some quick profiling, it seems to me the problem is actually in cvxpy not in cvxcanon, attached is a backreference chain for one of the objects that "leaks"

![image](https://cloud.githubusercontent.com/assets/591830/15601080/9d068bf0-23a2-11e6-8f69-02d9b77bfb50.png)

@SteveDiamond could it be that @memoize is storing things forever which leads to unbounded memory growth? Not sure why this would be different in python2 vs python3 though

**Comment by mwytock** [comment]
https://github.com/cvxgrp/cvxpy/issues/283
