### ISSUE TITLE
Segmentation fault after adding linear constraint in cvxpy

### ISSUE THREAD

**Issue by nkoep** [jacklzhu/CVXcanon#25]
Hey,

I encountered a segfault after adding a specific type of linear constraint in cvxpy. While the backtrace (see [here](https://gist.github.com/nkoep/486de1cdd8237d3fa9ed45919d5e1181)) points to one of Eigen's template methods, I figured it was most likely an issue in CVXcanon/cvxopt/cvxpy given the maturity of Eigen. Of course, that's just a guess and the issue could be caused elsewhere. Always hard to tell when it comes to segfaults.

A minimal working example can be found [here](https://gist.github.com/nkoep/ed361820ba473e7ef85e1c9d8e857463). Here's what python/cvx\* versions I'm using:

``` raw
[numberwang ⚡ ~] » python -V
Python 3.5.1
[numberwang ⚡ ~] » pip list | grep -i cvx
CVXcanon (0.0.23.4)
cvxopt (1.1.8)
cvxpy (0.4.0)
```

Some background on the problem: I'm trying to solve the basis pursuit problem on complex data with the additional constraint that the solution by conjugate symmetric so that its inverse Fourier transform be real-valued.

Regards

**Comment by mwytock** [comment]
Definitely seems to be an issue with negative indexing. We are working on a
fix, sorry about that

**Comment by SteveDiamond** [comment]
Update CVXcanon and the problem will be fixed.

**Comment by nkoep** [comment]
That did the trick. Thanks for fixing the issue at such short notice!
