### ISSUE TITLE
Clarify license and copyright

### ISSUE THREAD

**Issue by ilyagr** [jacklzhu/CVXcanon#28]
I wonder if you could clarify the copyright and license for CVXcanon. It would be great if you could put a copyright notice somewhere (does the copyright belong to Stanford? To the three authors?) and a copy of GPLv3 into the root directory.

I'd like to use newer versions of CVXPY in Google, but I can't until this is done. Thank you very much!

**Comment by SteveDiamond** [comment]
CVXcanon is Apache 2.0 licensed. I have the copyright, at least for the purpose of determining the license. I've added a license file and text to reflect this.

**Comment by ilyagr** [comment]
That should do it. Thank you very much! Ilya.
