### ISSUE TITLE
Cut a new pip release

### ISSUE THREAD

**Issue by bodono** [jacklzhu/CVXcanon#29]
The current version that's on PyPI is missing the fix in this merged PR https://github.com/cvxgrp/CVXcanon/pull/27

**Comment by showwin** [comment]
Hello, I need the fix #27.  
Could you please release the next version as soon as possible 🙏

**Comment by zhouwubai** [comment]
Same issue here.. Please

**Comment by KoenDierckx** [comment]
Same here

**Comment by SteveDiamond** [comment]
CVXcanon is now inside cvxpy. You shouldn't need it for anything.

**Comment by falaktheoptimist** [comment]
Could you please add this in the ReadMe? I was looking into how to use this library correctly to speedup cvxpy until I stumbled across this comment 😅

**Comment by singhavdeshk** [comment]
I am using older version of cvxpy==0.4.11 due to some large system dependency therefore I need this fix. Can we have a new version of cvxcanon please.

**Comment by SteveDiamond** [comment]
I pushed a new pip released.
