### ISSUE TITLE
Constraint offsets

### ISSUE THREAD

**Issue by SteveDiamond** [jacklzhu/CVXcanon#3]
Could you add an optional field `constr_offsets` to `canonInterface.get_problem_matrix` that takes a list of constraint offsets? In other words, if the argument to `constr_offsets` is `[3,5,7]` then constraint 0 starts at row 3, constraint 1 starts at row 5, and constraint 2 starts at row 7.

You might want to check that the offsets make sense, but it's also ok if you don't and just throw an error at some point. Another option would be for `constr_offsets` to expect a map of constraint id to offset. Either way is fine with me. The default behavior should be to assume all the constraints are stacked with no gaps, as in the current implementation.

This feature will make it much easier to handle parameters.

**Comment by millerjohnp** [comment]
I just added an optional field `constr_offsets` to `canonInterface.get_problem_matrix.` If the `const_offsets` argument is supplied, the function expects a list `[x_1, x_2, ..., x_n]`, where `x_i` is the vertical offset of the i-th constraint.

If a list is supplied, the code currently expects an offset for each constraint. Would this be sufficient to handle parameters? Or is the desired use case to only specify offsets for some subset of the constraints and then use the default stacking behavior for the other constraints?

In terms of error checking, would it be reasonable to assume the offset for constraint `i` is less than the offset for constraint `i+1`? Or can you imagine a case where the list of constraints would be something like `[10, 3, 12]`?

**Comment by SteveDiamond** [comment]
Thanks! Requiring offsets for every constraint is good. You can
assume/require that the constraints are monotonically increasing.

**Comment by millerjohnp** [comment]
Okay. I added error checking code and pushed the changes. I'm in the process of testing of the edge cases, but it's a bit difficult without modifying cvxpy too. Definitely let me know if you run into any issues!
