### ISSUE TITLE
osx Mojave compilation error

### ISSUE THREAD

**Issue by truggles** [jacklzhu/CVXcanon#33]
I was trying to install using `sudo -H pip install CVXcanon` on mac osx Mojave with XCode10.1 and running into compiler issues such as:

```
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from src/CVXcanon.cpp:16:
    src/CVXcanon.hpp:19:10: fatal error: 'vector' file not found
    #include <vector>
```

In the end I downloaded your source code and added:

```
    extra_link_args=["-stdlib=libc++",],
    extra_compile_args=["-mmacosx-version-min=10.9",]
```
to the Extensions of setup.py and was able to successfully compile using:
```
sudo -H pip install -e /Users/$USER/Downloads/CVXcanon-0.1.1/
```
I feel this solution is not generic enough to warrant a PR, but I thought I would let you know.

**Comment by SteveDiamond** [comment]
This is helpful, thanks! We found another way to fix this issue [here](https://github.com/cvxgrp/cvxpy/blob/master/setup.py).

**Comment by przemyslslaw** [comment]
I'm trying to install an older version of cvxpy on Mojave with fresh Anaconda via `pip install cvxpy==0.4.11` and I'm getting the same error.  What's the simplest way to deal with it?

**Comment by przemyslslaw** [comment]
Found the answer: it suffices to `export MACOSX_DEPLOYMENT_TARGET=10.9` before pip install.
