### ISSUE TITLE
Transfer this repo to cvxgrp

### ISSUE THREAD

**Issue by SteveDiamond** [jacklzhu/CVXcanon#4]
Could we transfer this repo to cvxgrp? That's where we have all the projects related to cvxpy, convex.jl, etc. I've invited all of you to join the group.

It's ok if you prefer not to transfer it, but it's easier to have a cvxpy dependency like this in the group.

Here's info about transferring a repo:
https://help.github.com/articles/transferring-a-repository/

**Comment by jacklzhu** [comment]
Sure thing! I'll do it now.
